spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/energyforecast
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
server.error.include-message=always
spring.mvc.problemdetails.enabled=false